
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        ItemType = _buf.ReadInt();
        MaxStack = _buf.ReadInt();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int ItemType;
    /// <summary>
    /// 最大堆叠数
    /// </summary>
    public readonly int MaxStack;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "itemType:" + ItemType + ","
        + "maxStack:" + MaxStack + ","
        + "}";
    }
}
}

